name: mlpc-project
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - python=3.12
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - h5py
  - pyspellchecker
  - seaborn
  - librosa
  - tqdm
  - pip
  - pip:
      - iterative-stratification